#version 450

layout(set = 0, binding = 0, rgba8) uniform image2D image;
layout(set = 0, binding = 1) uniform UniformBuffer
{
	vec4 color;
} uniformBuffer;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
	const ivec2 invocationID = ivec2(gl_GlobalInvocationID.xy);

	vec4 color = vec4(0.0, 0.0, 0.0, 1.0);

	if(invocationID.x % 8 > 1 || invocationID.y % 8 > 1)
	{
		color = uniformBuffer.color;
	}

	imageStore(image, invocationID, color);
}